### PR TITLE
Add route and route parameters to form annotation + Nulls in paginator

### PR DESCRIPTION
**Pull request by pmontoya**
Add route nulls to paginator
Merge mmoreram repository

Sorry for the previous PR, bad manipulation

### CODE REVIEW

**Comment by mmoreram** [comment]
@pmontoya 

This PR has two features (in the future, one issue per PR)
I have a problem here. I can merge one, but not the other one.

* NotNull - Is tested and well implemented. Congrats :)
* RouteAttributes - I cannot merge this feature like is done because introduces BC Break somehow. When you change the signature of a class or a method, or when you change an interface, then you must wait for a major version to introduce these changes. What you can do here is by using setters instead of constructor.

**Comment by pmontoya** [comment]
Sorry for the two features it was due to an emergency in a project.
RouteAttributes has been updated

**Comment by mmoreram** [comment]
@pmontoya checking :D Thanks!

**Comment by mmoreram** [comment]
The commit is meant to resolve the route and route_params in the form annotation as it's defined in the commit name, but the commit has the *IS NULL* in paginator as well.

Could you please split both features in two single commits please? I'm sure that the paginator is a good addition, but I'm not that sure in the form's one, so I think that the actor in charge of the action definition is not the form layer but the template layer...

Thanks.

**Comment by mmoreram** [comment]
@pmontoya and please, check why the tests are in red :(

**Pull request closed without merging**
