### PR TITLE
Feature/get post annotation

### PR DESCRIPTION
**Pull request by rogergros**
GET & POST annotation

Related: https://github.com/mmoreram/ControllerExtraBundle/issues/54

### CODE REVIEW

**Comment by rogergros** [comment]
Pls tag & :shipit: :dancer:

**Comment by mmoreram** [comment]
@rogergros Great implementation.

Could you please add some documentation?

**Comment by rogergros** [comment]
Sorry, annotation added @mmoreram :)

**Comment by mmoreram** [comment]
Thanks @rogergros. Checking & Merging :+1:

**Pull request merged**
