### PR TITLE
adding KNPPaginator support

### PR DESCRIPTION
**Pull request by ErikTrapman**
A bit earlier than I expected. Please review :)

### CODE REVIEW

**Comment by ErikTrapman** [comment]
Seems there's a HHVM-bug when mocking abstract classes: https://github.com/sebastianbergmann/phpunit-mock-objects/issues/223

**Comment by ErikTrapman** [comment]
Any idea how can I retry the travis-build?

**Comment by mmoreram** [comment]
@ErikTrapman done!

**Comment by ErikTrapman** [comment]
It still fails on that HHVM-issue which is fixed in https://github.com/facebook/hhvm/issues/5170. Maybe Travis hasnt updated its HHVM env yet.

**Comment by JHGitty** [comment]
The bug facebook/hhvm#5170 has been fixed for HHVM >= 3.8.0. The travis test runned with HHVM version 3.5.0. That is the reason.

**Comment by ErikTrapman** [comment]
Thanks for looking that up. All tests pass now.

**Pull request merged**
